export const folks = [
	{ id: 1, data: { name: 'Adam Pearce', page: 'https://roadtolarissa.com/', type: 'interactive', image: '/images/adam-pearce.png' } },
	{ id: 2, data: { name: 'Adrián Blanco', page: 'https://adrianblancoramos.com/', type: 'maps', image: '/images/adrian-blanco.png' } },
	{ id: 3, data: { name: 'Aileen Clarke', page: 'https://aileenclarke.github.io/', type: 'maps', image: '/images/aileen-clarke.png' } },
	{ id: 4, data: { name: 'Alba Martín', page: 'https://albamart.in/', type: 'interactive', image: '/images/alba-martin.png' } },
	{ id: 5, data: { name: 'Alberto Cairo', page: 'https://www.albertocairo.com/', type: 'mastermind', image: '/images/alberto-cairo.jpg' } },
	{ id: 6, data: { name: 'Alessia Musìo', page: 'https://alessiamusio.com/', type: 'designer', image: '/images/alessia-musio.png' } },
	{ id: 7, data: { name: 'Alli Torban', page: 'https://www.allitorban.com/', type: 'mastermind', image: '/images/alli-torban.png' } },
	{ id: 8, data: { name: 'Alvin Chang', page: 'https://alvinschang.com/', type: 'interactive', image: '/images/alvin-chang.png' } },
	{ id: 9, data: { name: 'Amelia Wattenberger', page: 'https://wattenberger.com/', type: 'mastermind', image: '/images/amelia-wattenberger.png' } },
	{ id: 10, data: { name: 'Amy Cesal', page: 'https://www.amycesal.com/', type: 'mastermind', image: '/images/amy-cesal.png' } },
	{ id: 11, data: { name: 'Andrea Giambelli', page: 'https://www.andreagiambelli.com/', type: 'interactive', image: '/images/andrea-giambelli.png' } },
	{ id: 12, data: { name: 'Arjun Kakkar', page: 'https://arjunkakkkar.mmm.page/', type: 'interactive', image: '/images/arjun-kakkar.png' } },
	{ id: 13, data: { name: 'Ashley Cai', page: 'https://www.ashleycai.com/', type: 'interactive', image: '/images/ashley-cai.png' } },
	{ id: 14, data: { name: 'Ben Tanen', page: 'https://ben-tanen.com/', type: 'mastermind', image: '/images/ben-tanen.png' } },
	{ id: 15, data: { name: 'Brody Smith', page: 'https://brody.fyi/', type: 'maps', image: '/images/brody-smith.png' } },
	{ id: 17, data: { name: 'Cam Rodriguez', page: 'https://camrodriguez.carrd.co/', type: 'maps', image: '/images/cam-rodriguez.png' } },
	{ id: 18, data: { name: 'Cédric Sam', page: 'https://cedric.sam.name/', type: 'maps', image: '/images/cedric-sam.png' } },
	{ id: 19, data: { name: 'Chris Canipe', page: 'https://chriscanipe.com/', type: 'interactive', image: '/images/chris-canipe.png' } },
	{ id: 20, data: { name: 'Connor Rothschild', page: 'https://www.connorrothschild.com/', type: 'mastermind', image: '/images/connor-rothschild.png' } },
	{ id: 21, data: { name: 'Daniel Gonzalez Cappa', page: 'https://gcappa.com/', type: 'designer', image: '/images/daniel-gonzalez-cappa.png' } },
	{ id: 22, data: { name: 'Dea Bankova', page: 'https://deabankova.com/', type: 'interactive', image: '/images/dea-bankova.png' } },
	{ id: 23, data: { name: 'Diana Estefanía Rubio', page: 'https://www.dianaestefaniarubio.com/', type: 'mastermind', image: '/images/diana-estefania-rubio.png' } },
	{ id: 24, data: { name: 'Diana Yukari', page: 'https://dianayukari.com/', type: 'designer', image: '/images/diana-yukari.png' } },
	{ id: 25, data: { name: 'Edit Gyenge', page: 'https://editgyenge.com/', type: 'designer', image: '/images/edit-gyenge.png' } },
	{ id: 26, data: { name: 'Eleanor Lutz', page: 'https://eleanorlutz.com/', type: 'designer', image: '/images/eleanor-lutz.png' } },
	{ id: 27, data: { name: 'Elena Mejía', page: 'https://elenaml.com/', type: 'interactive', image: '/images/elena-mejia.png' } },
	{ id: 29, data: { name: 'Elliot Bentley', page: 'https://elliotbentley.com/', type: 'interactive', image: '/images/elliot-bentley.png' } },
	{ id: 30, data: { name: 'Ethan Singer', page: 'https://ethansinger.me/', type: 'interactive', image: '/images/ethan-singer.png' } },
	{ id: 31, data: { name: 'Evelina Parrou', page: 'https://www.behance.net/evelinaj', type: 'designer', image: '/images/evelina-parrou.png' } },
	{ id: 32, data: { name: 'Federica Fragapane', page: 'https://www.behance.net/FedericaFragapane', type: 'mastermind', image: '/images/federica-fragapane.png' } },
	{ id: 33, data: { name: 'Florent Lavergne', page: 'https://www.behance.net/lavergneflor', type: 'maps', image: '/images/florent-lavergne.png' } },
	{ id: 34, data: { name: 'Gabrielle Merite', page: 'https://www.gabriellemerite.com/', type: 'mastermind', image: '/images/gabrielle-merite.png' } },
	{ id: 35, data: { name: 'Gemma Busquets', page: 'https://www.gemmabusquets.com/', type: 'mastermind', image: '/images/gemma-busquets.png' } },
	{ id: 36, data: { name: 'Giorgia Lupi', page: 'https://giorgialupi.com/', type: 'mastermind', image: '/images/giorgia-lupi.png' } },
	{ id: 37, data: { name: 'Gurman Bhatia', page: 'https://gurmanbhatia.com/', type: 'interactive', image: '/images/gurman-bhatia.png' } },
	{ id: 38, data: { name: 'Han Huang', page: 'https://jashcny.github.io/', type: 'interactive', image: '/images/han-huang.png' } },
	{ id: 39, data: { name: 'Ihar Yanouski', page: 'https://yanouski.com/', type: 'interactive', image: '/images/ihar-yanouski.png' } },
	{ id: 40, data: { name: 'Ilia Blinderman', page: 'https://iliablinderman.com/', type: 'interactive', image: '/images/ilia-blinderman.png' } },
	{ id: 41, data: { name: 'Irene de la Torre Arenas', page: 'https://irenedelatorrearenas.wordpress.com/', type: 'interactive', image: '/images/irene-de-la-torre-arenas.png' } },
	{ id: 42, data: { name: 'Jacopo Poletto', page: 'https://jacopopoletto.com/', type: 'interactive', image: '/images/jacopo-poletto.png' } },
	{ id: 43, data: { name: 'Jan Diehm', page: 'https://jandiehmdesigns.com/', type: 'interactive', image: '/images/jan-diehm.png' } },
	{ id: 44, data: { name: 'Jared Wilber', page: 'https://www.jwilber.me/', type: 'interactive', image: '/images/jared-wilber.png' } },
	{ id: 45, data: { name: 'Jeremy C.F. Lin', page: 'https://jeremycflin.github.io/', type: 'maps', image: '/images/jeremy-lin.png' } },
	{ id: 46, data: { name: 'Jin Wu', page: 'https://jinnwuu.github.io/portfolio/', type: 'maps', image: '/images/jin-wu.png' } },
	{ id: 47, data: { name: 'Joel Eastwood', page: 'http://joeleastwood.ca/', type: 'interactive', image: '/images/joel-eastwood.png' } },
	{ id: 48, data: { name: 'Joey Lee', page: 'https://jk-lee.com/', type: 'maps', image: '/images/joey-lee.png' } },
	{ id: 49, data: { name: 'Jonathan Corum', page: 'https://13pt.com/corum/', type: 'maps', image: '/images/jonathan-corum.png' } },
	{ id: 50, data: { name: 'Juan Pablo Bravo', page: 'https://www.linkedin.com/in/juanpablobravocl/', type: 'designer', image: '/images/juan-pablo-bravo.png' } },
	{ id: 51, data: { name: 'Judit Bekker', page: 'https://www.juditbekker.com/', type: 'interactive', image: '/images/judit-bekker.png' } },
	{ id: 52, data: { name: 'Kate Snow', page: 'https://katesnowdesign.com/', type: 'designer', image: '/images/kate-snow.png' } },
	{ id: 53, data: { name: 'Katie Marriner', page: 'https://katiemarriner.com/', type: 'interactive', image: '/images/katie-marriner.png' } },
	{ id: 55, data: { name: 'Kristin Baumann', page: 'https://www.kristin-baumann.com/', type: 'interactive', image: '/images/kristin-baumann.png' } },
	{ id: 56, data: { name: 'Krisztina Szucs', page: 'https://krisztinaszucs.com/', type: 'interactive', image: '/images/krisztina-szucs.png' } },
	{ id: 57, data: { name: 'Ksenia Orlova', page: 'https://www.behance.net/orlovakseniia', type: 'maps', image: '/images/ksenia-orlova.png' } },
	{ id: 58, data: { name: 'Laura Castro', page: 'https://www.iamlauracastro.com', type: 'interactive', image: '/images/laura-castro.png' } },
	{ id: 59, data: { name: 'Laura Martín', page: 'https://lmartingrx.github.io/porfolio/', type: 'interactive', image: '/images/laura-martin.png' } },
	{ id: 60, data: { name: 'Laura Navarro Soler', page: 'https://www.linkedin.com/in/laura-navarro-soler/', type: 'interactive', image: '/images/laura-navarro-soler.png' } },
	{ id: 61, data: { name: 'Leonardo Nicoletti', page: 'https://www.leonardonicoletti.com/', type: 'maps', image: '/images/leonardo-nicoletti.png' } },
	{ id: 62, data: { name: 'Lindsey Poulter', page: 'https://www.lindseypoulter.com/', type: 'interactive', image: '/images/lindsey-poulter.png' } },
	{ id: 63, data: { name: 'Lisa Charlotte Muth', page: 'https://lisacharlottemuth.com/', type: 'mastermind', image: '/images/lisa-charlotte-muth.png' } },
	{ id: 64, data: { name: 'Lisa Hornung', page: 'https://inside-numbers.com/', type: 'designer', image: '/images/lisa-hornung.png' } },
	{ id: 65, data: { name: 'Marcelo Duhalde', page: 'https://www.behance.net/marcelodc', type: 'designer', image: '/images/marcelo-duhalde.png' } },
	{ id: 66, data: { name: 'Marco Hernández', page: 'https://mhinfographics.com/', type: 'mastermind', image: '/images/marco-hernandez.png' } },
	{ id: 67, data: { name: 'Mariano Zafra', page: 'http://www.marianozafra.com/', type: 'maps', image: '/images/mariano-zafra.png' } },
	{ id: 68, data: { name: 'Marie Patino', page: 'https://mariepatino.com/', type: 'interactive', image: '/images/marie-patino.png' } },
	{ id: 69, data: { name: 'Marta Sierra', page: 'https://www.martaviz.nl/', type: 'hands', image: '/images/marta-sierra.png' } },
	{ id: 70, data: { name: 'Martin Grandjean', page: 'https://www.martingrandjean.ch/', type: 'mastermind', image: '/images/martin-grandjean.png' } },
	{ id: 71, data: { name: 'Martina Dossi', page: 'https://www.behance.net/martinadossi', type: 'designer', image: '/images/martina-dossi.png' } },
	{ id: 72, data: { name: 'Martina Zunica', page: 'https://www.behance.net/martinazunica_/', type: 'mastermind', image: '/images/martina-zunica.png' } },
	{ id: 73, data: { name: 'Matteo Palù', page: 'https://www.matteopalu.com/', type: 'designer', image: '/images/matteo-palu.png' } },
	{ id: 74, data: { name: 'Matteo Riva', page: 'https://crockhaus.com/', type: 'designer', image: '/images/matteo-riva.png' } },
	{ id: 75, data: { name: 'Matthew Daniels', page: 'https://matthewfdaniels.github.io/home/', type: 'interactive', image: '/images/matthew-daniels.png' } },
	{ id: 76, data: { name: 'Matthias Stahl', page: 'https://www.higsch.com/', type: 'mastermind', image: '/images/matthias-stahl.png' } },
	{ id: 77, data: { name: 'Michela Lazzaroni', page: 'https://www.behance.net/michelaz/projects', type: 'designer', image: '/images/michela-lazzaroni.png' } },
	{ id: 78, data: { name: 'Michelle McGhee', page: 'https://mmcghee.notion.site/Michelle-McGhee-b4e0346f98fd4cb988d025173c1e94a7/', type: 'interactive', image: '/images/michelle-mcGhee.png' } },
	{ id: 79, data: { name: 'Mira Rojanasakul', page: 'https://mirarojanasakul.com/', type: 'maps', image: '/images/mira-rojanasakul.png' } },
	{ id: 80, data: { name: 'Mohamad Waked', page: 'https://alhadaqa.com/', type: 'designer', image: '/images/mohamad-waked.png' } },
	{ id: 81, data: { name: 'Nadieh Bremer', page: 'https://www.visualcinnamon.com/', type: 'mastermind', image: '/images/nadieh-bremer.png' } },
	{ id: 82, data: { name: 'Nadja Popovich', page: 'https://nadjapopovich.com/', type: 'maps', image: '/images/nadja-popovich.png' } },
	{ id: 83, data: { name: 'Nathan Yau', page: 'https://flowingdata.com/', type: 'mastermind', image: '/images/nathan-yau.png' } },
	{ id: 84, data: { name: 'Nicholas Felton', page: 'https://feltron.com/', type: 'designer', image: '/images/nicholas-felton.png' } },
	{ id: 85, data: { name: 'Nikita Rokotyan', page: 'https://rokotyan.com/', type: 'interactive', image: '/images/nikita-rokotyan.png' } },
	{ id: 86, data: { name: 'Pablo Robles', page: 'https://www.josepablorobles.com/', type: 'maps', image: '/images/pablo-robles.png' } },
	{ id: 87, data: { name: 'Paul Murray', page: 'https://paulmurray.io/', type: 'interactive', image: '/images/paul-murray.png' } },
	{ id: 88, data: { name: 'Peter Cook', page: 'https://www.peterrcook.com/', type: 'interactive', image: '/images/peter-cook.png' } },
	{ id: 90, data: { name: 'Prinz Magtulis', page: 'https://www.prinzmagtulis.com/', type: 'interactive', image: '/images/prinz-magtulis.png' } },
	{ id: 92, data: { name: 'Rachael Dottle', page: 'https://rachaeldottle.com/', type: 'interactive', image: '/images/rachael-dottle.png' } },
	{ id: 93, data: { name: 'Rahul Mukherjee', page: 'https://www.rmukherjee.com/', type: 'interactive', image: '/images/rahul-mukherjee.png' } },
	{ id: 94, data: { name: 'Rosie Ettenheim', page: 'https://www.rosieettenheim.com/', type: 'designer', image: '/images/rosie-ettenheim.png' } },
	{ id: 95, data: { name: 'Ryan Best', page: 'https://ryanabest.com/', type: 'interactive', image: '/images/ryan-best.png' } },
	{ id: 98, data: { name: 'Sarah Fawson', page: 'https://thedatasays.org/', type: 'designer', image: '/images/sarah-fawson.png' } },
	{ id: 99, data: { name: 'Sarah Fossheim', page: 'https://fossheim.io/', type: 'mastermind', image: '/images/sarah-fossheim.png' } },
	{ id: 100, data: { name: 'Sarah Kay Miller', page: 'https://sarahkaymiller.com/', type: 'designer', image: '/images/sarah-kay-miller.png' } },
	{ id: 101, data: { name: 'Shirley Wu', page: 'https://shirleywu.studio/', type: 'interactive', image: '/images/shirley-wu.png' } },
	{ id: 104, data: { name: 'Simon Scarr', page: 'https://www.simonscarr.com/', type: 'designer', image: '/images/simon-scarr.png' } },
	{ id: 105, data: { name: 'Simone Betito', page: 'https://www.simonebetito.com/', type: 'interactive', image: '/images/simone-betito.png' } },
	{ id: 106, data: { name: 'Simran Parwani', page: 'https://simranparwani.github.io/', type: 'interactive', image: '/images/simran-parwani.png' } },
	{ id: 107, data: { name: 'Stefan Pullen', page: 'https://www.stefanpullen.com/', type: 'designer', image: '/images/stefan-pullen.png' } },
	{ id: 108, data: { name: 'Stefania Guerra', page: 'https://www.behance.net/stegue88e47f', type: 'designer', image: '/images/stefania-guerra.png' } },
	{ id: 111, data: { name: 'Taylor Maggiacomo', page: 'https://www.taylormaggiacomo.com/', type: 'designer', image: '/images/taylor-maggiacomo.png' } },
	{ id: 112, data: { name: 'Thomas Oide', page: 'https://thomasoide.github.io/', type: 'interactive', image: '/images/thomas-oide.png' } },
	{ id: 113, data: { name: 'Tiziana Alocci', page: 'https://www.tizianaalocci.com/', type: 'designer', image: '/images/tiziana-alocci.png' } },
	{ id: 116, data: { name: 'Weiyi Cai', page: 'https://www.caiweiyi.com/', type: 'maps', image: '/images/weiyi-cai.png' } },
	{ id: 117, data: { name: 'Wendy Shijia', page: 'https://wendyshijia.notion.site/', type: 'maps', image: '/images/wendy-shijia.png' } },
	{ id: 118, data: { name: 'Will Chase', page: 'https://www.williamrchase.com/', type: 'interactive', image: '/images/will-chase.png' } },
	{ id: 119, data: { name: 'Wilson Andrews', page: 'https://www.wilsonmarkandrews.com/', type: 'interactive', image: '/images/wilson-andrews.png' } },
	{ id: 120, data: { name: 'Yaryna Serkez', page: 'https://yarynam.github.io/', type: 'interactive', image: '/images/yaryna-serkez.png' } },
	{ id: 121, data: { name: 'Yi Zhe Ang', page: 'https://yizhe-ang.github.io/', type: 'interactive', image: '/images/yi-zhe-ang.png' } },
	{ id: 122, data: { name: 'Zach Levitt', page: 'https://zachlevitt.com/', type: 'maps', image: '/images/zach-levitt.png' } },
	{ id: 123, data: { name: 'Curran Kelleher', page: 'https://github.com/curran ', type: 'mastermind', image: '/images/curran-kelleher.png' } }
  ];