export const folks = [
	{ id: 1, data: { name: 'Adam Pearce', page: 'https://roadtolarissa.com/', type: 'interactive', image: './images/adam-pearce.webp' } },
	{ id: 2, data: { name: 'Adrián Blanco', page: 'https://adrianblancoramos.com/', type: 'maps', image: './images/adrian-blanco.webp' } },
	{ id: 3, data: { name: 'Aileen Clarke', page: 'https://aileenclarke.github.io/', type: 'maps', image: './images/aileen-clarke.webp' } },
	{ id: 4, data: { name: 'Alba Martín', page: 'https://albamart.in/', type: 'interactive', image: './images/alba-martin.webp' } },
	{ id: 5, data: { name: 'Alberto Cairo', page: 'https://www.albertocairo.com/', type: 'mastermind', image: './images/alberto-cairo.webp' } },
	{ id: 6, data: { name: 'Alessia Musìo', page: 'https://alessiamusio.com/', type: 'designer', image: './images/alessia-musio.webp' } },
	{ id: 7, data: { name: 'Alli Torban', page: 'https://www.allitorban.com/', type: 'mastermind', image: './images/alli-torban.webp' } },
	{ id: 8, data: { name: 'Alvin Chang', page: 'https://alvinschang.com/', type: 'interactive', image: './images/alvin-chang.webp' } },
	{ id: 9, data: { name: 'Amelia Wattenberger', page: 'https://wattenberger.com/', type: 'mastermind', image: './images/amelia-wattenberger.webp' } },
	{ id: 10, data: { name: 'Amy Cesal', page: 'https://www.amycesal.com/', type: 'mastermind', image: './images/amy-cesal.webp' } },
	{ id: 11, data: { name: 'Andrea Giambelli', page: 'https://www.andreagiambelli.com/', type: 'interactive', image: './images/andrea-giambelli.webp' } },
	{ id: 12, data: { name: 'Arjun Kakkar', page: 'https://arjunkakkkar.mmm.page/', type: 'interactive', image: './images/arjun-kakkar.webp' } },
	{ id: 13, data: { name: 'Ashley Cai', page: 'https://www.ashleycai.com/', type: 'interactive', image: './images/ashley-cai.webp' } },
	{ id: 14, data: { name: 'Ben Tanen', page: 'https://ben-tanen.com/', type: 'mastermind', image: './images/ben-tanen.webp' } },
	{ id: 15, data: { name: 'Brody Smith', page: 'https://brody.fyi/', type: 'maps', image: './images/brody-smith.webp' } },
	{ id: 17, data: { name: 'Cam Rodriguez', page: 'https://camrodriguez.carrd.co/', type: 'maps', image: './images/cam-rodriguez.webp' } },
	{ id: 18, data: { name: 'Cédric Sam', page: 'https://cedric.sam.name/', type: 'maps', image: './images/cedric-sam.webp' } },
	{ id: 19, data: { name: 'Chris Canipe', page: 'https://chriscanipe.com/', type: 'interactive', image: './images/chris-canipe.webp' } },
	{ id: 20, data: { name: 'Connor Rothschild', page: 'https://www.connorrothschild.com/', type: 'mastermind', image: './images/connor-rothschild.webp' } },
	{ id: 21, data: { name: 'Daniel Gonzalez Cappa', page: 'https://gcappa.com/', type: 'designer', image: './images/daniel-gonzalez-cappa.webp' } },
	{ id: 22, data: { name: 'Dea Bankova', page: 'https://deabankova.com/', type: 'interactive', image: './images/dea-bankova.webp' } },
	{ id: 23, data: { name: 'Diana Estefanía Rubio', page: 'https://www.dianaestefaniarubio.com/', type: 'mastermind', image: './images/diana-estefania-rubio.webp' } },
	{ id: 24, data: { name: 'Diana Yukari', page: 'https://dianayukari.com/', type: 'designer', image: './images/diana-yukari.webp' } },
	{ id: 25, data: { name: 'Edit Gyenge', page: 'https://editgyenge.com/', type: 'designer', image: './images/edit-gyenge.webp' } },
	{ id: 26, data: { name: 'Eleanor Lutz', page: 'https://eleanorlutz.com/', type: 'designer', image: './images/eleanor-lutz.webp' } },
	{ id: 27, data: { name: 'Elena Mejía', page: 'https://elenaml.com/', type: 'interactive', image: './images/elena-mejia.webp' } },
	{ id: 29, data: { name: 'Elliot Bentley', page: 'https://elliotbentley.com/', type: 'interactive', image: './images/elliot-bentley.webp' } },
	{ id: 30, data: { name: 'Ethan Singer', page: 'https://ethansinger.me/', type: 'interactive', image: './images/ethan-singer.webp' } },
	{ id: 31, data: { name: 'Evelina Parrou', page: 'https://www.behance.net/evelinaj', type: 'designer', image: './images/evelina-parrou.webp' } },
	{ id: 32, data: { name: 'Federica Fragapane', page: 'https://www.behance.net/FedericaFragapane', type: 'mastermind', image: './images/federica-fragapane.webp' } },
	{ id: 33, data: { name: 'Florent Lavergne', page: 'https://www.behance.net/lavergneflor', type: 'maps', image: './images/florent-lavergne.webp' } },
	{ id: 34, data: { name: 'Gabrielle Merite', page: 'https://www.gabriellemerite.com/', type: 'mastermind', image: './images/gabrielle-merite.webp' } },
	{ id: 35, data: { name: 'Gemma Busquets', page: 'https://www.gemmabusquets.com/', type: 'mastermind', image: './images/gemma-busquets.webp' } },
	{ id: 36, data: { name: 'Giorgia Lupi', page: 'https://giorgialupi.com/', type: 'mastermind', image: './images/giorgia-lupi.webp' } },
	{ id: 37, data: { name: 'Gurman Bhatia', page: 'https://gurmanbhatia.com/', type: 'interactive', image: './images/gurman-bhatia.webp' } },
	{ id: 38, data: { name: 'Han Huang', page: 'https://jashcny.github.io/', type: 'interactive', image: './images/han-huang.webp' } },
	{ id: 39, data: { name: 'Ihar Yanouski', page: 'https://yanouski.com/', type: 'interactive', image: './images/ihar-yanouski.webp' } },
	{ id: 40, data: { name: 'Ilia Blinderman', page: 'https://iliablinderman.com/', type: 'interactive', image: './images/ilia-blinderman.webp' } },
	{ id: 41, data: { name: 'Irene de la Torre Arenas', page: 'https://irenedelatorrearenas.wordpress.com/', type: 'interactive', image: './images/irene-de-la-torre-arenas.webp' } },
	{ id: 42, data: { name: 'Jacopo Poletto', page: 'https://jacopopoletto.com/', type: 'interactive', image: './images/jacopo-poletto.webp' } },
	{ id: 43, data: { name: 'Jan Diehm', page: 'https://jandiehmdesigns.com/', type: 'interactive', image: './images/jan-diehm.webp' } },
	{ id: 44, data: { name: 'Jared Wilber', page: 'https://www.jwilber.me/', type: 'interactive', image: './images/jared-wilber.webp' } },
	{ id: 45, data: { name: 'Jeremy C.F. Lin', page: 'https://jeremycflin.github.io/', type: 'maps', image: './images/jeremy-lin.webp' } },
	{ id: 46, data: { name: 'Jin Wu', page: 'https://jinnwuu.github.io/portfolio/', type: 'maps', image: './images/jin-wu.webp' } },
	{ id: 47, data: { name: 'Joel Eastwood', page: 'http://joeleastwood.ca/', type: 'interactive', image: './images/joel-eastwood.webp' } },
	{ id: 48, data: { name: 'Joey Lee', page: 'https://jk-lee.com/', type: 'maps', image: './images/joey-lee.webp' } },
	{ id: 49, data: { name: 'Jonathan Corum', page: 'https://13pt.com/corum/', type: 'maps', image: './images/jonathan-corum.webp' } },
	{ id: 50, data: { name: 'Juan Pablo Bravo', page: 'https://www.linkedin.com/in/juanpablobravocl/', type: 'designer', image: './images/juan-pablo-bravo.webp' } },
	{ id: 51, data: { name: 'Judit Bekker', page: 'https://www.juditbekker.com/', type: 'interactive', image: './images/judit-bekker.webp' } },
	{ id: 52, data: { name: 'Kate Snow', page: 'https://katesnowdesign.com/', type: 'designer', image: './images/kate-snow.webp' } },
	{ id: 53, data: { name: 'Katie Marriner', page: 'https://katiemarriner.com/', type: 'interactive', image: './images/katie-marriner.webp' } },
	{ id: 55, data: { name: 'Kristin Baumann', page: 'https://www.kristin-baumann.com/', type: 'interactive', image: './images/kristin-baumann.webp' } },
	{ id: 56, data: { name: 'Krisztina Szucs', page: 'https://krisztinaszucs.com/', type: 'interactive', image: './images/krisztina-szucs.webp' } },
	{ id: 57, data: { name: 'Ksenia Orlova', page: 'https://www.behance.net/orlovakseniia', type: 'maps', image: './images/ksenia-orlova.webp' } },
	{ id: 58, data: { name: 'Laura Castro', page: 'https://www.iamlauracastro.com', type: 'interactive', image: './images/laura-castro.webp' } },
	{ id: 59, data: { name: 'Laura Martín', page: 'https://lmartingrx.github.io/porfolio/', type: 'interactive', image: './images/laura-martin.webp' } },
	{ id: 60, data: { name: 'Laura Navarro Soler', page: 'https://www.linkedin.com/in/laura-navarro-soler/', type: 'interactive', image: './images/laura-navarro-soler.webp' } },
	{ id: 61, data: { name: 'Leonardo Nicoletti', page: 'https://www.leonardonicoletti.com/', type: 'maps', image: './images/leonardo-nicoletti.webp' } },
	{ id: 62, data: { name: 'Lindsey Poulter', page: 'https://www.lindseypoulter.com/', type: 'interactive', image: './images/lindsey-poulter.webp' } },
	{ id: 63, data: { name: 'Lisa Charlotte Muth', page: 'https://lisacharlottemuth.com/', type: 'mastermind', image: './images/lisa-charlotte-muth.webp' } },
	{ id: 64, data: { name: 'Lisa Hornung', page: 'https://inside-numbers.com/', type: 'designer', image: './images/lisa-hornung.webp' } },
	{ id: 65, data: { name: 'Marcelo Duhalde', page: 'https://www.behance.net/marcelodc', type: 'designer', image: './images/marcelo-duhalde.webp' } },
	{ id: 66, data: { name: 'Marco Hernández', page: 'https://mhinfographics.com/', type: 'mastermind', image: './images/marco-hernandez.webp' } },
	{ id: 67, data: { name: 'Mariano Zafra', page: 'http://www.marianozafra.com/', type: 'maps', image: './images/mariano-zafra.webp' } },
	{ id: 68, data: { name: 'Marie Patino', page: 'https://mariepatino.com/', type: 'interactive', image: './images/marie-patino.webp' } },
	{ id: 69, data: { name: 'Marta Sierra', page: 'https://www.martaviz.nl/', type: 'hands', image: './images/marta-sierra.webp' } },
	{ id: 70, data: { name: 'Martin Grandjean', page: 'https://www.martingrandjean.ch/', type: 'mastermind', image: './images/martin-grandjean.webp' } },
	{ id: 71, data: { name: 'Martina Dossi', page: 'https://www.behance.net/martinadossi', type: 'designer', image: './images/martina-dossi.webp' } },
	{ id: 72, data: { name: 'Martina Zunica', page: 'https://www.behance.net/martinazunica_/', type: 'mastermind', image: './images/martina-zunica.webp' } },
	{ id: 73, data: { name: 'Matteo Palù', page: 'https://www.matteopalu.com/', type: 'designer', image: './images/matteo-palu.webp' } },
	{ id: 74, data: { name: 'Matteo Riva', page: 'https://crockhaus.com/', type: 'designer', image: './images/matteo-riva.webp' } },
	{ id: 75, data: { name: 'Matthew Daniels', page: 'https://matthewfdaniels.github.io/home/', type: 'interactive', image: './images/matthew-daniels.webp' } },
	{ id: 76, data: { name: 'Matthias Stahl', page: 'https://www.higsch.com/', type: 'mastermind', image: './images/matthias-stahl.webp' } },
	{ id: 77, data: { name: 'Michela Lazzaroni', page: 'https://www.behance.net/michelaz/projects', type: 'designer', image: './images/michela-lazzaroni.webp' } },
	{ id: 78, data: { name: 'Michelle McGhee', page: 'https://mmcghee.notion.site/Michelle-McGhee-b4e0346f98fd4cb988d025173c1e94a7/', type: 'interactive', image: './images/michelle-mcGhee.webp' } },
	{ id: 79, data: { name: 'Mira Rojanasakul', page: 'https://mirarojanasakul.com/', type: 'maps', image: './images/mira-rojanasakul.webp' } },
	{ id: 80, data: { name: 'Mohamad Waked', page: 'https://alhadaqa.com/', type: 'designer', image: './images/mohamad-waked.webp' } },
	{ id: 81, data: { name: 'Nadieh Bremer', page: 'https://www.visualcinnamon.com/', type: 'mastermind', image: './images/nadieh-bremer.webp' } },
	{ id: 82, data: { name: 'Nadja Popovich', page: 'https://nadjapopovich.com/', type: 'maps', image: './images/nadja-popovich.webp' } },
	{ id: 83, data: { name: 'Nathan Yau', page: 'https://flowingdata.com/', type: 'mastermind', image: './images/nathan-yau.webp' } },
	{ id: 84, data: { name: 'Nicholas Felton', page: 'https://feltron.com/', type: 'designer', image: './images/nicholas-felton.webp' } },
	{ id: 85, data: { name: 'Nikita Rokotyan', page: 'https://rokotyan.com/', type: 'interactive', image: './images/nikita-rokotyan.webp' } },
	{ id: 86, data: { name: 'Pablo Robles', page: 'https://www.josepablorobles.com/', type: 'maps', image: './images/pablo-robles.webp' } },
	{ id: 87, data: { name: 'Paul Murray', page: 'https://paulmurray.io/', type: 'interactive', image: './images/paul-murray.webp' } },
	{ id: 88, data: { name: 'Peter Cook', page: 'https://www.peterrcook.com/', type: 'interactive', image: './images/peter-cook.webp' } },
	{ id: 90, data: { name: 'Prinz Magtulis', page: 'https://www.prinzmagtulis.com/', type: 'interactive', image: './images/prinz-magtulis.webp' } },
	{ id: 92, data: { name: 'Rachael Dottle', page: 'https://rachaeldottle.com/', type: 'interactive', image: './images/rachael-dottle.webp' } },
	{ id: 93, data: { name: 'Rahul Mukherjee', page: 'https://www.rmukherjee.com/', type: 'interactive', image: './images/rahul-mukherjee.webp' } },
	{ id: 94, data: { name: 'Rosie Ettenheim', page: 'https://www.rosieettenheim.com/', type: 'designer', image: './images/rosie-ettenheim.webp' } },
	{ id: 95, data: { name: 'Ryan Best', page: 'https://ryanabest.com/', type: 'interactive', image: './images/ryan-best.webp' } },
	{ id: 98, data: { name: 'Sarah Fawson', page: 'https://thedatasays.org/', type: 'designer', image: './images/sarah-fawson.webp' } },
	{ id: 99, data: { name: 'Sarah Fossheim', page: 'https://fossheim.io/', type: 'mastermind', image: './images/sarah-fossheim.webp' } },
	{ id: 100, data: { name: 'Sarah Kay Miller', page: 'https://sarahkaymiller.com/', type: 'designer', image: './images/sarah-kay-miller.webp' } },
	{ id: 101, data: { name: 'Shirley Wu', page: 'https://shirleywu.studio/', type: 'interactive', image: './images/shirley-wu.webp' } },
	{ id: 104, data: { name: 'Simon Scarr', page: 'https://www.simonscarr.com/', type: 'designer', image: './images/simon-scarr.webp' } },
	{ id: 105, data: { name: 'Simone Betito', page: 'https://www.simonebetito.com/', type: 'interactive', image: './images/simone-betito.webp' } },
	{ id: 106, data: { name: 'Simran Parwani', page: 'https://simranparwani.github.io/', type: 'interactive', image: './images/simran-parwani.webp' } },
	{ id: 107, data: { name: 'Stefan Pullen', page: 'https://www.stefanpullen.com/', type: 'designer', image: './images/stefan-pullen.webp' } },
	{ id: 108, data: { name: 'Stefania Guerra', page: 'https://www.behance.net/stegue88e47f', type: 'designer', image: './images/stefania-guerra.webp' } },
	{ id: 111, data: { name: 'Taylor Maggiacomo', page: 'https://www.taylormaggiacomo.com/', type: 'designer', image: './images/taylor-maggiacomo.webp' } },
	{ id: 112, data: { name: 'Thomas Oide', page: 'https://thomasoide.github.io/', type: 'interactive', image: './images/thomas-oide.webp' } },
	{ id: 113, data: { name: 'Tiziana Alocci', page: 'https://www.tizianaalocci.com/', type: 'designer', image: './images/tiziana-alocci.webp' } },
	{ id: 116, data: { name: 'Weiyi Cai', page: 'https://www.caiweiyi.com/', type: 'maps', image: './images/weiyi-cai.webp' } },
	{ id: 117, data: { name: 'Wendy Shijia', page: 'https://wendyshijia.notion.site/', type: 'maps', image: './images/wendy-shijia.webp' } },
	{ id: 118, data: { name: 'Will Chase', page: 'https://www.williamrchase.com/', type: 'interactive', image: './images/will-chase.webp' } },
	{ id: 119, data: { name: 'Wilson Andrews', page: 'https://www.wilsonmarkandrews.com/', type: 'interactive', image: './images/wilson-andrews.webp' } },
	{ id: 120, data: { name: 'Yaryna Serkez', page: 'https://yarynam.github.io/', type: 'interactive', image: './images/yaryna-serkez.webp' } },
	{ id: 121, data: { name: 'Yi Zhe Ang', page: 'https://yizhe-ang.github.io/', type: 'interactive', image: './images/yi-zhe-ang.webp' } },
	{ id: 122, data: { name: 'Zach Levitt', page: 'https://zachlevitt.com/', type: 'maps', image: './images/zach-levitt.webp' } },
	{ id: 123, data: { name: 'Curran Kelleher', page: 'https://github.com/curran ', type: 'mastermind', image: './images/curran-kelleher.webp' } },
	{ id: 124, data: { name: 'Moritz Stefaner', page: 'https://truth-and-beauty.net/', type: 'interactive', image: './images/moritz-stefaner.webp' } },
	{ id: 125, data: { name: 'Fernando Becerra', page: 'https://www.fernandobecerra.com/', type: 'interactive', image: './images/fernando-becerra.webp' } },
	{ id: 126, data: { name: 'Harry Stevens', page: 'https://harryjstevens.com/', type: 'mastermind', image: './images/harry-stevens.webp' } },
	{ id: 127, data: { name: 'Nami Sumida', page: 'https://namisumida.github.io/', type: 'interactive', image: './images/nami-sumida.webp' } },
];
